"""LaTeX tables and the per-task figure for the full report, computed from results/ and runs/.

    python scripts/make_tables.py

Writes report/tables/*.tex and report/figures/dose_per_task.pdf. Nothing in these tables is typed
by hand except the column headers and the values reported in the SmolVLA paper.
"""

from __future__ import annotations

import glob
import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from vla_stress.analysis import plots
from vla_stress.analysis.results import load
from vla_stress.analysis.stats import mcnemar_exact, wilson

T = Path("report/tables")
T.mkdir(parents=True, exist_ok=True)
S = Path("results/summary")


def fmt(k, n, ci=True):
    lo, hi = wilson(k, n)
    s = f"{k}/{n} ({100 * k / n:.0f}\\%)"
    return s + f" [{100 * lo:.0f}, {100 * hi:.0f}]" if ci else s


def write(name, body):
    (T / f"{name}.tex").write_text("% generated by scripts/make_tables.py -- do not edit\n" + body)
    print("wrote", T / f"{name}.tex")


# ------------------------------------------------------------------ baselines (+ per task)
bs, bg = load("baseline_spatial"), load("baseline_goal")
chk = json.load(open("results/lerobot_eval_check.json"))
k_chk = sum(sum(t["metrics"]["successes"]) for t in chk["per_task"])
n_chk = sum(len(t["metrics"]["successes"]) for t in chk["per_task"])
ids = [t["task_id"] for t in chk["per_task"]]
ours = bs[bs.task_id.isin(ids)]
rows = [
    ("LIBERO-Spatial", bs, "90\\%"),
    ("LIBERO-Goal", bg, "92\\%"),
]
body = "\\begin{tabular}{lccc}\n\\toprule\nSuite & This work (10 tasks $\\times$ 10) & Reported~\\citep{shukor2025smolvla} \\\\\n\\midrule\n"
for name, d, rep in rows:
    body += f"{name} & {fmt(int(d.success.sum()), len(d))} & {rep} \\\\\n"
body += "\\midrule\n"
body += (
    f"\\multicolumn{{3}}{{l}}{{\\footnotesize Cross-check on Spatial tasks {ids[0]} and {ids[1]}: "
    f"\\texttt{{lerobot-eval}} {k_chk}/{n_chk}, this loop {int(ours.success.sum())}/{len(ours)}.}} \\\\\n"
)
body += "\\bottomrule\n\\end{tabular}\n"
write("baselines", body.replace("{lccc}", "{lcc}"))

# per-task baseline (appendix)
body = "\\begin{tabular}{l" + "c" * 10 + "c}\n\\toprule\nTask & " + " & ".join(str(i) for i in range(10)) + " & All \\\\\n\\midrule\n"
for name, d in [("Spatial", bs), ("Goal", bg)]:
    r = d.groupby("task_id").success.sum()
    body += name + " & " + " & ".join(f"{int(r.get(i, 0))}" for i in range(10)) + f" & {int(d.success.sum())}/{len(d)} \\\\\n"
body += "\\bottomrule\n\\end{tabular}\n"
write("baselines_per_task", body)

# ------------------------------------------------------------------ breaking points
bp = pd.read_csv(S / "breaking_points.csv")
meta = {
    "camera_orbit": ("Camera orbit", "deg", "gradual"),
    "robot_init": ("Arm initial pose", "rad", "tolerance, then cliff"),
    "light_dimming": ("Lighting", "fraction off", "threshold"),
    "image_noise": ("Pixel noise", "noise std", "threshold"),
}
extra = {"robot_init": ["dose_robot_init_fine"], "light_dimming": ["dose_light_dimming_fine"], "camera_orbit": ["dose_camera_orbit_wide"]}


def g(v):
    return f"{v:.3g}" if np.isfinite(v) else "--"


body = "\\begin{tabular}{lccl}\n\\toprule\nPerturbation (unit) & Logistic $x_{50}$ & Model-free $x_{50}$ & Shape \\\\\n\\midrule\n"
for _, r in bp.iterrows():
    name, unit, shape = meta[r.family]
    parts = [load(n) for n in [f"dose_{r.family}"] + extra.get(r.family, [])]
    d = pd.concat([p for p in parts if p is not None])
    levels = sorted(d.magnitude.unique())
    lv = f"{len(levels) + 1} (0--{levels[-1]:g})"
    hi_mf = g(r.x50_interp_hi) if np.isfinite(r.x50_interp_hi) else f"$>${levels[-1]:g}"
    mf = g(r.x50_interp) if np.isfinite(r.x50_interp) else f"$>${levels[-1]:g}"
    body += f"{name} ({unit}) & {g(r.x50)} [{g(max(r.x50_lo, 0))}, {g(r.x50_hi)}] & {mf} [{g(r.x50_interp_lo)}, {hi_mf}] & {shape} \\\\\n"
body += "\\bottomrule\n\\end{tabular}\n"
write("breaking_points", body)

# ------------------------------------------------------------------ residual RL
v_ho, v_tr = load("rl_eval_vla"), load("rl_eval_train_vla")
seeds = sorted(Path(f).stem.split("_")[-1] for f in glob.glob("results/rl_eval_residual_s*.csv"))
res_ho = {sd: load(f"rl_eval_residual_{sd}") for sd in seeds}
res_tr = {sd: load(f"rl_eval_train_residual_{sd}") for sd in seeds if load(f"rl_eval_train_residual_{sd}") is not None}
rseeds = sorted("rand_" + Path(f).stem.split("_")[-1] for f in glob.glob("results/rl_eval_residual_rand_s*.csv"))
for sd in rseeds:
    res_ho[sd] = load(f"rl_eval_residual_{sd}")
    if load(f"rl_eval_train_residual_{sd}") is not None:
        res_tr[sd] = load(f"rl_eval_train_residual_{sd}")
all_seeds = seeds + rseeds
rp = load("rl_eval_replan10")


def kn(d, mag):
    if d is None:
        return None
    x = d[np.isclose(d.magnitude, mag)]
    return (int(x.success.sum()), len(x)) if len(x) else None


def cell(t):
    return "--" if t is None else f"{t[0]}/{t[1]}"


groups = [("Seen (0--19)", "0.05", v_tr, res_tr, 0.05, None), ("Held-out (40--49)", "0.05", v_ho, res_ho, 0.05, rp), ("Held-out (40--49)", "0", v_ho, res_ho, 0.0, rp), ("Held-out (40--49)", "0.10", v_ho, res_ho, 0.10, rp)]
cols = "ll" + "c" * (2 + len(all_seeds))
head = "Initial states & Offset (rad) & VLA & " + " & ".join(f"{sd}" if not sd.startswith("rand") else f"r{sd[-2:]}" for sd in all_seeds) + " & Re-plan / 10 \\\\\n"
body = f"\\begin{{tabular}}{{{cols}}}\n\\toprule\n" + head + "\\midrule\n"
for lab, off, v, res, mag, rpl in groups:
    body += f"{lab} & {off} & {cell(kn(v, mag))} & " + " & ".join(cell(kn(res.get(sd), mag)) for sd in all_seeds) + f" & {cell(kn(rpl, mag))} \\\\\n"
# episode length of successes and McNemar p at the training level
body += "\\midrule\n"
for lab, v, res in [("Seen", v_tr, res_tr), ("Held-out", v_ho, res_ho)]:
    lens, ps = [], []
    for sd in all_seeds:
        r = res.get(sd)
        if r is None:
            lens.append("--")
            ps.append("--")
            continue
        m = v[np.isclose(v.magnitude, 0.05)].merge(r[np.isclose(r.magnitude, 0.05)], on="episode", suffixes=("_v", "_r"))
        lens.append(f"{m[m.success_r == 1].steps_r.mean():.0f}")
        ps.append(f"{mcnemar_exact(m.success_v, m.success_r)['p']:.2f}")
    vl = v[np.isclose(v.magnitude, 0.05)]
    body += f"\\multicolumn{{2}}{{l}}{{{lab}: steps per success}} & {vl[vl.success == 1].steps.mean():.0f} & " + " & ".join(lens) + " & \\\\\n"
    body += f"\\multicolumn{{2}}{{l}}{{{lab}: McNemar $p$ vs VLA}} & & " + " & ".join(ps) + " & \\\\\n"
body += "\\bottomrule\n\\end{tabular}\n"
write("rl_results", body)

# PPO hyperparameters, read from the checkpoints actually used
ck = torch.load(sorted(glob.glob("runs/robot025_task2_s*/final.pt"))[0], map_location="cpu", weights_only=False)["args"]
hp = [
    ("Task / perturbation", f"Spatial task {ck['task']}, arm offset {0.2 * ck['intensity']:.2f} rad/joint"),
    ("Correction scale $\\alpha$", ck["alpha"]),
    ("Policy / value network", f"MLP, 2 $\\times$ {ck['hidden']} tanh, separate"),
    ("Initial std of $\\Delta a$", f"$e^{{{ck['init_log_std']:g}}}$"),
    ("Parallel environments", ck["n_envs"]),
    ("Steps per env per rollout", ck["rollout_steps"]),
    ("Total environment steps", f"{ck['total_steps']:,}".replace(",", "\\,")),
    ("Epochs / minibatch", f"{ck['epochs']} / {ck['minibatch']}"),
    ("Learning rate (Adam)", ck["lr"]),
    ("$\\gamma$ / GAE $\\lambda$", f"{ck['gamma']} / {ck['gae_lambda']}"),
    ("Clip / value coef. / entropy coef.", f"{ck['clip']} / {ck['vf_coef']} / {ck['ent_coef']}"),
    ("Max grad norm", ck["max_grad_norm"]),
    ("VLA actions per chunk executed", ck["n_action_steps"]),
    ("Training init states", f"0--{ck['train_init_states'] - 1}"),
]
body = "\\begin{tabular}{ll}\n\\toprule\n" + "".join(f"{a} & {b} \\\\\n" for a, b in hp) + "\\bottomrule\n\\end{tabular}\n"
write("ppo_hparams", body)

# ------------------------------------------------------------------ compute
exp = [
    ("Baselines", ["baseline_spatial", "baseline_goal"]),
    ("Listening matrix", ["language_matrix"]),
    ("Instruction variants", ["language_variants"]),
    ("Dose-response (4 families)", ["dose_camera_orbit", "dose_camera_orbit_wide", "dose_robot_init", "dose_robot_init_fine", "dose_light_dimming", "dose_light_dimming_fine", "dose_image_noise"]),
    ("Camera masking", ["camera_mask"]),
    ("Instruction canonicalisation", ["language_canonical", "language_spatial_paraphrases", "language_spatial_canonical"]),
    ("Residual RL evaluation", ["rl_eval_vla", "rl_eval_train_vla", "rl_eval_replan10", "rl_zero_check"] + [f"rl_eval_residual_{sd}" for sd in all_seeds] + [f"rl_eval_train_residual_{sd}" for sd in all_seeds]),
    ("Validation re-runs", ["repro_check"]),
]
body = "\\begin{tabular}{lrrr}\n\\toprule\nExperiment & Episodes & s / episode & Hours \\\\\n\\midrule\n"
tot_n, tot_h = 0, 0.0
for lab, names in exp:
    ds = [x for x in (load(n) for n in names) if x is not None]
    if not ds:
        continue
    d = pd.concat(ds)
    h = d.duration_s.sum() / 3600
    tot_n += len(d)
    tot_h += h
    body += f"{lab} & {len(d)} & {d.duration_s.mean():.0f} & {h:.1f} \\\\\n"
# failure search: durations are stored per episode inside the search and validation files
qd_p, qv_p = Path("results/qd_search.csv"), Path("results/qd_validation.csv")
if qd_p.exists():
    qd = pd.read_csv(qd_p)
    eps = [e for js in qd.episodes for e in json.loads(js)]
    durs = [e.get("duration_s", np.nan) for e in eps]
    n_qd = len(eps)
    if qv_p.exists():
        qv = pd.read_csv(qv_p)
        n_qd += len(qv)
        durs += list(qv.get("duration_s", pd.Series([np.nan] * len(qv))))
    h = np.nansum(durs) / 3600
    tot_n += n_qd
    tot_h += h
    body += f"Failure search (MAP-Elites) & {n_qd} & {np.nanmean(durs):.0f} & {h:.1f} \\\\\n"
ppo_h = 0.0
for f in glob.glob("runs/robot025_task2_s*/log.csv") + glob.glob("runs/robot025_task2_rand_s*/log.csv"):
    try:
        lg = pd.read_csv(f)
    except pd.errors.EmptyDataError:
        continue  # run just started
    if len(lg):
        steps = lg.step.diff().fillna(lg.step.iloc[0])
        ppo_h += float((steps / lg.sps).sum()) / 3600
body += f"PPO training ({len(all_seeds)} runs) & -- & -- & {ppo_h:.1f} \\\\\n"
body += f"\\midrule\nTotal & {tot_n} & & {tot_h + ppo_h:.1f} \\\\\n\\bottomrule\n\\end{{tabular}}\n"
write("compute", body)
json.dump({"episodes": tot_n, "eval_hours": round(tot_h, 1), "ppo_hours": round(ppo_h, 1)}, open(S / "compute.json", "w"))

# ------------------------------------------------------------------ per-task dose figure
curves = {}
for fam in ["camera_orbit", "robot_init", "light_dimming", "image_noise"]:
    parts = [load(n) for n in [f"dose_{fam}"] + extra.get(fam, [])]
    d = pd.concat([p for p in parts if p is not None])
    zero = bs[bs.episode.isin(d.episode.unique())].copy()
    zero["magnitude"] = 0.0
    curves[fam] = pd.concat([zero, d], ignore_index=True)
plots.dose_per_task(curves, "report/figures/dose_per_task.pdf")
print("wrote report/figures/dose_per_task.pdf")

# ------------------------------------------------------------------ macros used in the full report
n_seeds = len(seeds)
macros = {
    "AllEpisodes": f"{tot_n:,}".replace(",", "\\,"),
    "EvalHours": f"{tot_h:.0f}",
    "PPOHours": f"{ppo_h:.0f}",
    "TotalHours": f"{tot_h + ppo_h:.0f}",
    "NSeeds": str(n_seeds),
    "SeedsWord": {1: "one", 2: "two", 3: "three"}.get(n_seeds, str(n_seeds)),
}
(T / "macros.tex").write_text("% generated by scripts/make_tables.py\n" + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in macros.items()))
print("wrote", T / "macros.tex")
